---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  deleteAfter: "false"
  env: stage
  owner: company-DevOps
  product: infra-k8s
  stream: company
  temporary: "false"
resources:
  - ../../base/infra-core/external-dns.yaml
  - ../../base/infra-core/external-dns-cloudflare.yaml
  - ../../base/infra-core/aws-lb-controller.yaml
  - ../../base/infra-core/aws-ebs-csi-driver.yaml
  - ../../base/infra-core/cluster-autoscaler.yaml
  - ../../base/infra-core/vector-agent.yaml
  - ../../base/infra-core/shell-operator.yaml
  - vault
  - external-secrets
patchesStrategicMerge:
  - external-dns.yaml
  - external-dns-cloudflare.yaml
  - aws-lb-controller.yaml
  - aws-ebs-csi-driver.yaml
  - cluster-autoscaler.yaml
  - vector-agent.yaml
