---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: infra-core
spec:
  chart:
    spec:
      version: "0.7.2"
      interval: 30m
  values:
    replicaCount: 2
    podLabels:
      env: stage
      jira: companySTREAM-18688
    webhook:
      podLabels:
        env: stage
        jira: companySTREAM-18688
    certController:
      podLabels:
        env: stage
        jira: companySTREAM-18688
