---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: strimzi-vault-secrets
  namespace: infra-core
spec:
  data:
  - remoteRef:
      key: company/strimzi-auth
      property: bootstrap_external
    secretKey: bootstrap_external
  - remoteRef:
      key: company/strimzi-auth
      property: password
    secretKey: password
  - remoteRef:
      key: company/strimzi-auth
      property: username
    secretKey: username
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: company-ro-cluster-secret-store
  target:
    name: strimzi-vault-secrets
