---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: banzaicloud-stable
  namespace: flux-system
spec:
  interval: 1h0m
  url: https://kubernetes-charts.banzaicloud.com
