app:
  appName: "service1-api-job-processor"

  service:
    enabled: true
    type: ClusterIP
    ports:
      http-public:
        externalPort: 8080
        internalPort: 8080
        protocol: TCP
      monitoring:
        externalPort: 8081
        internalPort: 8081
        protocol: TCP

  livenessProbe:
    enabled: true
    mode: httpGet
    httpGet:
      port: 8081
      path: "/health"

  readinessProbe:
    enabled: true
    mode: httpGet
    httpGet:
      port: 8081
      path: "/ready"

  configmap:
    NAMESPACE: project
    OTEL_SERVICE_NAME: service1-api-job-processor
    OTEL_COLLECTOR_GRPC_ADDR: "agent.monitoring.svc:4317"

    COBRA_COMMAND: "job-processor"

    SERVER_HEALTH_PORT: 8081

    EXAMPLE_JOB_IS_ENABLED: true

  secrets:
    MONGO_URI: "/global/rotatorv2/mongo/uri"
    MONGO_USER: "/global/rotatorv2/mongo/user"
    MONGO_PASSWORD: "/global/rotatorv2/mongo/password"
    MONGO_DB: "/global/rotatorv2/mongo/database"
