---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ID:role/sops-company-prod-main-oidc
  name: kustomize-controller
  namespace: flux-system
