---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ../../base/flux-system/slack-alert.yaml
  - ../../base/flux-system/slack-provider.yaml
  - secrets
patchesStrategicMerge:
  - slack-provider.yaml
