apiVersion: v1
kind: Secret
metadata:
    name: sre-kafka-credentials
    namespace: infra-core
stringData:
    brokers: b-1.sre-logs.3ypn1v.c5.kafka.eu-central-1.amazonaws.com:9096,b-4.sre-logs.3ypn1v.c5.kafka.eu-central-1.amazonaws.com:9096,b-6.sre-logs.3ypn1v.c5.kafka.eu-central-1.amazonaws.com:9096
    login: company-logs
    password: ENC[AES256_GCM,data:XqtCt6nZKg==,iv:gdKMWCtHfOh5opP3kiIUDq0CYCgs/NEWcbvnehGkkm0=,tag:T1n8LaY4Yy9P1FIHfGaMPQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:ID:alias/vault-kms-prod
          created_at: "2022-11-04T10:50:14Z"
          enc: AQICAHjujYkfYCPLziWNrTkT0Q2X0fuj0qSc7AU3TddW+Y2frgEz00vXWgvK9mls4BgwrGmyAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMg/VEOq9KNPlOIQRmAgEQgDsgKdmYnh+ISrEDqFFVxrkSRucmPJ7qhq8ittouzIfdSmo9w/maSjAUPUdJn/fGvdKIoczHnDQH68cPoQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-04T10:50:15Z"
    mac: ENC[AES256_GCM,data:cZBch1tAOlNAzwed0nQ9T8N/rW9LHmRZ6iPiAeRSZRk+TqVdAb0qo+hRNn684MB+lKui7yHAL3VW9YFT6up/IKqbabE7pEs7LfSVcBUqBgQra9NpbJYvO97k9f2XcxtPr77GNDU0OW8um9F5hfCw10v1WFVUNbe44z4hnJq4lng=,iv:CTkobXaryKXh3IlAJMUhyGJ/NPpfGrruwSF1ictFC6Q=,tag:MDFjfzT7qXwAWaCZWfj9+Q==,type:str]
    pgp: []
    encrypted_regex: password
    version: 3.7.3
