---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: th

resources:
  - ../../base/th/content-studio.yaml
  - ../../base/th/template-renderer.yaml

patchesStrategicMerge:
  - content-studio.yaml
  - template-renderer.yaml
