---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
  namespace: infra-core
  labels:
    app: cluster-autoscaler
    jira: "companySTREAM-17142"
spec:
  interval: 10m
  chart:
    spec:
      chart: cluster-autoscaler
      version: '9.21.1'
      sourceRef:
        kind: HelmRepository
        name: cluster-autoscaler
        namespace: flux-system
      interval: 24h
  values:
    image:
      tag: "v1.22.3"
    additionalLabels:
      owner: company-devops
      stream: company
      app: cluster-autoscaler
      product: observability
      env: prod
      temporary: "false"
      deleteAfter: "false"
    awsRegion: eu-central-1
    cloudProvider: aws
    autoDiscovery:
      clusterName: company-prod-main
    extraArgs:
      v: 4
      stderrthreshold: info
      logtostderr: true
      write-status-configmap: true
      leader-elect: true
      skip-nodes-with-local-storage: false
      scale-down-enabled: true
      balance-similar-node-groups: true
      scale-down-utilization-threshold: 0.85
      scale-down-non-empty-candidates-count: 5
      max-node-provision-time: 5m0s
      scan-interval: 10s
      scale-down-delay-after-add: 10m
      scale-down-delay-after-delete: 0s
      scale-down-delay-after-failure: 3m
      scale-down-unneeded-time: 5m
      skip-nodes-with-system-pods: false
      expander: least-waste
      # max-graceful-termination-sec: 60
    replicaCount: 2
    resources:
      limits:
        cpu: 0.2
        memory: 1Gi
      requests:
        cpu: 0.2
        memory: 1Gi
    rbac:
      serviceAccount:
        create: false
        name: cluster-autoscaler
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::ID:role/cluster-autoscaler-company-prod-main-oidc
    serviceMonitor:
      enabled: true
    priorityClassName: system-cluster-critical
