---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: infra-core
spec:
  chart:
    spec:
      chart: external-dns
      version: "6.28.4"
  values:
    domainFilters:
      - company.corp.loc
    podLabels:
      env: prod
    metrics:
      enabled: false
