---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: infra-core
spec:
  values:
    commonLabels:
      env: prod
    podLabels:
      env: prod
    customConfig:
      transforms:
        kubernetes_json_logs_create_topic:
          source: |-
            .topic_key, err = "logs.company.prod." + .kubernetes.pod_namespace
            .kubernetes.pod_namespace, err = "company-" + .kubernetes.pod_namespace
