apiVersion: v1
data:
    DATABASE_PASSWORD: ENC[AES256_GCM,data:4YenUrVO8dfJWbpIepwU+g==,iv:1++ZIryUDG49F2zqOW0fzTVRH1ZiF3sxZZJZZbKvY5g=,tag:QGsR7KSOTZoox+LxEzrNeA==,type:str]
    DATABASE_USER: ENC[AES256_GCM,data:nX31xjs0hT8tU5amije6cKY=,iv:u8XXII4whghjkemafSS0B0Vhe1Rg49krPOQO2qHf0q0=,tag:VobDL8FFeLIGWKU74JSIYg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: db-auth-content-studio
    namespace: th
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:ID:alias/vault-kms-prod
          created_at: "2023-11-22T21:12:32Z"
          enc: AQICAHhB3ALNLeZo91htOFIfIg6ls4VzgNq0Sx75zFNU9X2FlgHIQJko8RxgIUGNpliYL5wzAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMIZrkElciw9rlGLeuAgEQgDvZId0RvbS4TNz3lTjpo6GYIvajMUpPVOJeYVygMZbvAaT9Wbf9ORJBTm1BFDWVNdpC1kckII07XvUO+A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-22T21:12:34Z"
    mac: ENC[AES256_GCM,data:cPtGVE/GOTsgZC/mLi8chxHG/gsD0SHmaFqt4Zi+TIRv5+7T4CSyicDeZzSDjsuSsa+mm8X9xNr/suPLqT+po4LK/QoPbU3TPQW4QtNg5e7Jejf5tzFB9NHuill+a2aHYWQceexZZBOaVCM0f4txDtxoSsbKy+SBiCpK7FV8Qg0=,iv:stQ1b7LLtFVpT9Zvus+A6HLICjZVsy3MdBIEjR3w2nc=,tag:4gJESvGM7twhF2BVkUaNEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.8.1
