---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: k8s-internal-services-endpoint
    alb.ingress.kubernetes.io/load-balancer-name: k8s-internal-services-endpoint
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:eu-central-1:627992770327:certificate/eb4c1866-3128-4a19-b554-816be1d44202'
    # alb.ingress.kubernetes.io/security-groups: sg-0519b89297f7a54a2,sg-0e1c3149d3e40f949
    alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
    alb.ingress.kubernetes.io/tags: stream=company,owner=company-devops,terraform=false
    alb.ingress.kubernetes.io/healthcheck-port: '10254'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '10'
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: '*.company-stage.corp.loc'
  name: k8s-internal-services-endpoint-alb
  namespace: ingress-nginx
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: ingress-nginx-controller
                port:
                  number: 80
