---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  releaseName: vault
  chart:
    spec:
      chart: vault
      version: '0.19.0'
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
      interval: 24h0m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    global:
      enabled: true
      imagePullSecrets: []
      tlsDisable: true
    injector:
      enabled: true
      externalVaultAddr: "https://vault.nonprod-sre.corp.loc/"
      replicas: 3
      leaderElector:
        enabled: true
      image:
        repository: "hashicorp/vault-k8s"
        tag: "0.16.1"
        pullPolicy: IfNotPresent
      agentImage:
        repository: "git.corp.com:4567/sre/vault-init"
        tag: "1.9.2"
      metrics:
        enabled: true
      extraLabels:
        owner: sre
        app: vault-injector
        stream: sre
        product: vault
      authPath: "auth/kubernetes-aws-company"
      logLevel: "info"
      logFormat: "json"
      revokeOnShutdown: true
      namespaceSelector:
        matchExpressions:
          - key: vault-injector-webhook
            operator: NotIn
            values:
              - disabled
      certs:
        secretName: null
        caBundle: ""
        certName: tls.crt
        keyName: tls.key
      resources:
        limits:
          memory: 64Mi
          cpu: 64m
        requests:
          memory: 64Mi
          cpu: 64m
