---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-webhook
  namespace: vault
spec:
  releaseName: vault-secrets-webhook
  interval: 10m
  chart:
    spec:
      chart: vault-secrets-webhook
      version: '1.15.11'
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-stable
        namespace: flux-system
  values:
    namespaceSelector:
      matchLabels:
        bank-vault-injector: enabled
    secretsFailurePolicy: Fail
    configMapFailurePolicy: Fail
    customResourcesFailurePolicy: Fail
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    labels:
      owner: sre
      app: bank-vault-injector
      stream: sre
      product: vault
