name: (private) Build Development Docker Images

on:
  workflow_call:
    inputs:
      docker_repository:
        description: Docker repository name, e.g. `LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY` when using GAR.
        type: string
        required: true
      multi_platform:
        description: Produce multi-platform images (e.g. amd64, and arm64)
        type: boolean
        default: false

jobs:
  # NOTE: that inline dispatching `if: inputs.multi_platform` is work around
  # reusable workflow stack depth limit https://github.com/orgs/community/discussions/8488
  #
  # Invalid workflow file: .github/workflows/default.yaml#L48
  # error parsing called workflow
  # ".github/workflows/default.yaml"
  # -> "./.github/workflows/images.yaml"
  # --> "./.github/workflows/images-dev.yaml"
  # ---> "./.github/workflows/images-dev-mp.yaml"
  # : job "python-builder" calls workflow "./.github/workflows/docker-build-mp.yaml", but doing so would exceed the limit on called workflow depth of 3

  python-builder:
    if: ${{inputs.multi_platform}}
    name: Python Builder (multi-platform)
    uses: ./.github/workflows/docker-build-mp.yaml
    secrets: inherit
    with:
      context: ./infra
      build-contexts: |
        python=docker-image://${{inputs.docker_repository}}/python:sha-${{github.sha}}
      file: ./infra/docker/dev/python-builder.dockerfile
      image: ${{inputs.docker_repository}}/python-builder
      title: Python Builder

  dev-sp:
    if: ${{!inputs.multi_platform}}
    name: Dev
    runs-on: [standard-2-amd64]
    steps:
      - name: Sudo GitHub Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{vars.SUDO_GHA_APP_ID}}
          installation_id: ${{vars.SUDO_GHA_APP_INSTALLATION_ID}}
          private_key: ${{secrets.SUDO_GHA_APP_PRIVATE_KEY}}

      - name: Checkout
        uses: actions/checkout@v4

      - name: CI Metadata
        id: meta
        uses: ./.github/actions/metadata
        with:
          sudo-token: ${{steps.generate_token.outputs.token}}

      - name: Setup Buildx
        uses: ./.github/actions/setup-buildx

      - name: Python Builder (GHA, and Devbox environment)
        uses: ./.github/actions/docker-build
        with:
          context: ./infra
          build-contexts: |
            python=docker-image://${{inputs.docker_repository}}/python:sha-${{github.sha}}
          file: ./infra/docker/dev/python-builder.dockerfile
          image: ${{inputs.docker_repository}}/python-builder
          tags: ${{steps.meta.outputs.docker_tags}}
