---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: infra-core
spec:
  releaseName: external-secrets
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: '0.7.2'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
      interval: 24h0m0s
  values:
    replicaCount: 2
    leaderElect: true
    podLabels:
      app: external-secrets
      owner: company-devops
      stream: company
      jira: companySTREAM-18688
    serviceMonitor:
      enabled: true
    webhook:
      create: true
      replicaCount: 1
      failurePolicy: Fail
      serviceMonitor:
        enabled: true
      podLabels:
        app: external-secrets
        stream: company
        owner: company-devops
        jira: companySTREAM-18688
    certController:
      create: true
      serviceMonitor:
        enabled: true
      podLabels:
        app: external-secrets
        stream: company
        owner: company-devops
        jira: companySTREAM-18688
