---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  labels:
    env: stage
    owner: company-devops
    stream: company
  name: kubernetes-system-alerts
  namespace: monitoring
spec:
  groups:
    - name: kubernetes-system
      rules:
        - alert: KubeVersionMismatch
          annotations:
            description: There are {{ $value }} different semantic versions of Kubernetes components running.
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeversionmismatch
            summary: Different semantic versions of Kubernetes components running.
          expr: |
            count(count by (git_version) (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"},"git_version","$1","git_version","(v[0-9]*.[0-9]*).*"))) > 1
          for: 15m
          labels:
            severity: warning
            namespace: monitoring
            owner: company-devops
            stream: company
        - alert: KubeClientErrors
          annotations:
            description: Kubernetes API server client '{{ $labels.job }}/{{ $labels.instance }}' is experiencing {{ $value | humanizePercentage }} errors.'
            runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclienterrors
            summary: Kubernetes API server client is experiencing errors.
          expr: |
            (sum(rate(rest_client_requests_total{code=~"5.."}[5m])) by (instance, job, namespace)
              /
            sum(rate(rest_client_requests_total[5m])) by (instance, job, namespace))
            > 0.01
          for: 15m
          labels:
            severity: warning
            namespace: monitoring
            owner: company-devops
            stream: company
        - alert: KubeAPIErrors
          annotations:
            description: Kubernetes API server 403 errors rate is high
            runbook_url: https://git.corp.com/DevOps/runbook/-/blob/master/docs/uncategorized/kubernetes.md#eks-api-server-errors
            summary: Kubernetes API server 403 errors rate is high
          expr: |
            sum (rate(apiserver_request_total{code="403"}[5m])) / sum (rate(apiserver_request_total[5m])) * 100 > 3
          for: 1m
          labels:
            severity: warning
            namespace: monitoring
            owner: company-devops
            stream: company
        - alert: KubeAPIErrors
          annotations:
            description: Kubernetes API server 50X errors rate is high
            runbook_url: https://git.corp.com/DevOps/runbook/-/blob/master/docs/uncategorized/kubernetes.md#eks-api-server-errors
            summary: Kubernetes API server 50X errors rate is high
          expr: |
            sum (rate(apiserver_request_total{code=~"50."}[5m])) / sum (rate(apiserver_request_total[5m])) * 100 > 0
          for: 1m
          labels:
            severity: warning
            namespace: monitoring
            owner: company-devops
            stream: company
        - alert: KubeWebHookRejection
          annotations:
            description: Kubernetes webhook rejection inscreased
            runbook_url: https://git.corp.com/DevOps/runbook/-/blob/master/docs/uncategorized/kubernetes.md#webhook-errors
            summary: Kubernetes webhook rejection inscreased
          expr: |
            increase(apiserver_admission_webhook_rejection_count{error_type!="no_error"}[1m]) > 0
          for: 0m
          labels:
            severity: critical
            namespace: monitoring
            owner: company-devops
            stream: company
