---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - general.yaml
  - kube-state-metrics.yaml
  - kubelet-rules.yaml
  - kubernetes-apps-rules.yaml
  - kubernetes-apps.yaml
  - kubernetes-resources.yaml
  - kubernetes-storage.yaml
  - kubernetes-system-kubelet.yaml
  - kubernetes-system.yaml
  - node-exporter-rules.yaml
  - node-exporter.yaml
