apiVersion: v2
name: service1-api-app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: app
    version: 3.1.19
    repository: "https://corp.github.io/k8app"