name: 'Docker Build'
description: |-
  This action wraps `docker/build-push-action`, to ensure that
  all docker images build by Fatmouse pipelines follow same patterns.

  It's expected that `Buildx` is already installed with `docker/setup-buildx-action`.

inputs:
  context:
    description: Build's context
    required: true
  file:
    description: Path to the Dockerfile.
    required: true
  image:
    description: Image name
    required: true
  build-contexts:
    description: List of additional build contexts (e.g., name=path)
  build-args:
    description: List of build-time variables
  tags:
    description: Semver tagging strategy. Default none. (see https://github.com/docker/metadata-action#typesemver)

runs:
  using: composite
  steps:
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{inputs.image}}
        tags: ${{inputs.tags}}
        labels: |
          net.scalr.commit-sha=${{github.sha}}

    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: ${{inputs.context}}
        build-contexts: ${{inputs.build-contexts}}
        build-args: ${{inputs.build-args}}
        file: ${{inputs.file}}
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
        cache-from: type=registry,ref=${{inputs.image}}-buildcache
        cache-to: type=registry,ref=${{inputs.image}}-buildcache
        platforms: linux/amd64
        load: false
        push: true
