---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-rds-metadata-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-rds-metadata-exporter
  template:
    metadata:
      labels:
        app: aws-rds-metadata-exporter
        env: preprod
        jira: companySTREAM-23730
        owner: company-devops
        product: observability
        stream: company
    spec:
      # Managed via Terraform
      serviceAccount: aws-rds-metadata-exporter
      imagePullSecrets:
        - name: deploy-secret
      containers:
        - image: git.corp.com:4567/sre/aws-resource-metadata-exporter:v0.0.6-125f5847
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          name: aws-rds-metadata-exporter
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aws-rds-metadata-exporter
  name: aws-rds-metadata-exporter
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: aws-rds-metadata-exporter
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-aws-metadata-rds-exporter
  namespace: monitoring
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /metrics
      scrapeTimeout: 30s
      targetPort: 9090
      relabelings:
        - sourceLabels: [instance]
          targetLabel: dimension_DBInstanceIdentifier
  jobLabel: aws-rds-metadata-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app: aws-rds-metadata-exporter
