---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  releaseName: metrics-server
  interval: 30m
  timeout: 15m
  maxHistory: 3
  chart:
    spec:
      chart: metrics-server
      version: 3.8.4
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 24h0m0s
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    imagePullSecrets:
      - name: deploy-secret
    podLabels:
      owner: company-devops
      stream: company
      app: metrics-server
      product: observability
      jira: companySTREAM-23730
      temporary: "false"
      deleteAfter: "false"
    replicas: 1
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 100m
        memory: 256Mi

    defaultArgs:
      - --cert-dir=/tmp
      - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
      - --kubelet-use-node-status-port
      - --metric-resolution=15s
      - --kubelet-insecure-tls

    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false

    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1

    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - metrics-server
              topologyKey: kubernetes.io/hostname
            weight: 100
    rbac:
      create: true
      pspEnabled: false
    podDisruptionBudget:
      enabled: false
