---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-operator
      version: '0.9.0'
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: flux-system
      interval: 24h
  values:
    extraLabels:
      app: victoriametrics-operator
      jira: companySTREAM-13089
      owner: company-devops
      stream: company
      env: stage
      product: observability
      temporary: 'false'
      deleteAfter: 'false'
    podLabels:
      app: victoriametrics-operator
      jira: companySTREAM-13089
      owner: company-devops
      stream: company
      env: stage
      product: observability
      temporary: 'false'
      deleteAfter: 'false'
    image:
      repository: victoriametrics/operator
      tag: v0.28.3
      pullPolicy: IfNotPresent
    createCRD: true
    useLegacyCRD: false
    replicaCount: 1
    logLevel: "info"
    rbac:
      create: true
      pspEnabled: true
    operator:
      # -- By default, operator converts prometheus-operator objects.
      disable_prometheus_converter: false
      # -- By default, operator creates psp for its objects.
      psp_auto_creation_enabled: false
      # -- Enables ownership reference for converted prometheus-operator objects,
      # it will remove corresponding victoria-metrics objects in case of deletion prometheus one.
      enable_converter_ownership: true
      # -- Enables custom config-reloader, bundled with operator.
      # It should reduce  vmagent and vmauth config sync-time and make it predictable.
      useCustomConfigReloader: true

    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 128Mi

    # -- Pod's node selector. Ref: [https://kubernetes.io/docs/user-guide/node-selection/]
    nodeSelector: {}
    tolerations: []
    # -- Pod affinity
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - victoria-metrics-operator
              topologyKey: kubernetes.io/hostname
            weight: 100

    # TO DO deploy cert manager
    admissionWebhooks:
      # -- Enables validation webhook.
      enabled: false
      # -- What to do in case, when operator not available to validate request.
      policy: Fail
      # -- Enables custom ca bundle, if you are not using cert-manager.
      # -- in case of custom ca, you have to create secret - {{chart-name}}-validation
      # -- with keys: tls.key, tls.crt, ca.crt
      caBundle: ""
      certManager:
        # -- Enables cert creation and injection by cert-manager.
        enabled: false
        # --If needed, provide own issuerName. Operator will create self-signed if empty.
        issuerName: ""

    ## Extra Env Vars for changing default limits of Configreloader. They are specific for VMAgent!
    ## All vars can be found here https://github.com/VictoriaMetrics/operator/blob/master/vars.MD
    env:
      - name: VM_VMALERTDEFAULT_CONFIGRELOADERCPU
        value: 250m
      - name: VM_VMALERTDEFAULT_CONFIGRELOADERMEMORY
        value: 50Mi
      - name: VM_VMAGENTDEFAULT_CONFIGRELOADERCPU
        value: 250m
      - name: VM_VMAGENTDEFAULT_CONFIGRELOADERMEMORY
        value: 100Mi
