---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../base/monitoring/prometheus-operator.yaml
  - ../../base/monitoring/cronjob-prometheus-operator-rules.yaml
  - ../../base/monitoring/vm-operator.yaml
  - ../../base/monitoring/vm-agent.yaml
  - ../../base/monitoring/vm-cluster.yaml
  - ../../base/monitoring/vm-alert.yaml
  - ../../base/monitoring/aws-rds-metadata-exporter.yaml
  - ../../base/monitoring/prometheus-yace-exporter.yaml
  - ../../base/monitoring/metrics-server.yaml
  - vm-ingress.yaml
  - vm-additional-scrape-config.yaml
patchesStrategicMerge:
  - vm-operator.yaml
  - vm-agent.yaml
  - vm-cluster.yaml
  - vm-alert.yaml
  - prometheus-operator.yaml
  - aws-rds-metadata-exporter.yaml
  - prometheus-yace-exporter.yaml
  - metrics-server.yaml
