---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      version: 3.8.4
  interval: 24h
  values:
    podLabels:
      env: prod

    resources:
      requests:
        cpu: 20m
        memory: 100Mi
      limits:
        memory: 200Mi
