---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  values:
    commonLabels:
      prometheus: prometheus-k8s-stage
      env: stage

    prometheus-node-exporter:
      podLabels:
        env: stage

    alertmanager:
      alertmanagerSpec:
        podMetadata:
          labels:
            env: stage
      ingress:
        enabled: true
        hosts:
          - alertmanager.company-stage.corp.loc
        annotations:
          kubernetes.io/ingress.class: 'alb'
          alb.ingress.kubernetes.io/group.name: "k8s-internal-monitoring-endpoint"
          alb.ingress.kubernetes.io/tags: "stream=company,owner=company-devops,terraform=false"
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
          alb.ingress.kubernetes.io/scheme: 'internal'
          alb.ingress.kubernetes.io/success-codes: '200'
          alb.ingress.kubernetes.io/target-type: 'ip'
          alb.ingress.kubernetes.io/inbound-cidrs: 10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
        paths:
          - /*

      config:
        global:
          resolve_timeout: 5m
        route:
          group_by: ["alertname"]
          receiver: "monitoring-aws-stage-company"
          repeat_interval: 1h
          routes:
            - receiver: monitoring-aws-stage-company
              matchers:
                - alertname=~"^.*"
              continue: false
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 4h

        receivers:

          # Shared AWS-PROD-company alerts
          - name: "monitoring-aws-stage-company"
            slack_configs:
              - api_url: "https://hooks.slack.com/services///"
                channel: "#monitoring-aws-stage-company"
                send_resolved: true
                title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Monitoring Event Notification'
                text: >-
                  {{ range .Alerts }}
                    *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
                    *Details:*
                    {{ .Annotations.description }}
                    {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                    {{ end }}
                  {{ end }}
