---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-operator
spec:
  chart:
    spec:
      version: '0.9.0'
  values:
    extraLabels:
      env: stage
    podLabels:
      env: stage
    image:
      repository: victoriametrics/operator
      tag: v0.28.3
    replicaCount: 2
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 128Mi
