---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service1-api-app
  namespace: kube-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: service1-api-app
spec:
  project: project
  source:
    repoURL: https://git.corp.tech/gitops/services/project/com/k8s.git
    targetRevision: HEAD
    path: services/service1-api/app

    helm:
      parameters:
        - name: "app.serviceExternal.enabled"
          value: "false"
      valueFiles:
        - values.default.yaml
        - values.dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: false
    retry:
      backoff:
        duration: "10s"
        factor: 2
        maxDuration: "3m"
      limit: 10
    syncOptions:
      - "Validate=false" # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default )
      - "PrunePropagationPolicy=foreground" # Supported policies are background, foreground and orphan.
      - "PruneLast=true" # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
      - "RespectIgnoreDifferences=true" # Respect ignored fields from '$app.ignoreDifferences'
