apiVersion: v1
kind: Secret
metadata:
    name: sre-kafka-credentials
    namespace: infra-core
stringData:
    brokers: b-1.srelogs.h7q617.c8.kafka.eu-central-1.amazonaws.com:9096,b-2.srelogs.h7q617.c8.kafka.eu-central-1.amazonaws.com:9096,b-3.srelogs.h7q617.c8.kafka.eu-central-1.amazonaws.com:9096
    login: company-logs
    password: ENC[AES256_GCM,data:bgLYS2wy0pnwrCXOdQKJIQ==,iv:E7aD0Um9hcTmmTj7R10a6eKvDyMh6GpGImA43311wpY=,tag:EeYuwMeXVDe4w8UrzBaBWA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:627992770327:alias/vault-kms-stage
          created_at: "2022-10-25T11:52:03Z"
          enc: AQICAHgauyOKvqqgBm6sbN1IAccCtERv7Fn9lXlWc6J58oOM0AFlfgFC0lTTKRb4ROGQkBeHAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMPJPKHjFs+kGBwCLTAgEQgDvFDS5lKwWdjcqnxCqi5k6821blyratEHyaeACGrn7n/HOfjnccJS9x96anmIGL1cCATgmH5AIkvLDFBg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-10-25T11:52:04Z"
    mac: ENC[AES256_GCM,data:P4lTf0i2BimonLJLsdON/824Pbkt5/G5xffSdfxMAA9r8obnVaf9W3FQMkFxNvnrm0Py4A2CzCKp/8FDBeP0kmW87s5XmxvsRDBQ39jzX9GW36dGmjw253eM8ZX5XS9yOBh4NMRmKRQZHjhcWIEIdsdsX5I7kJYxUX+r2N4Pzp8=,iv:GpumzeLBqiIqPYsYLNPRfIscompKGla/vaL4EwPem5PDo=,tag:MTgDEYsfO3rdF5ckt0azWg==,type:str]
    pgp: []
    encrypted_regex: password
    version: 3.7.3
